image: node:alpine  // 默认的ci部署的docker镜像

stages:  // 首先按顺序定义有几个步骤。步骤下面的所有job是同步执行的
  - build
  
job1:
  stage: build  // 属于test的stage
  script:
    - cd client && npm run build // 这个job执行的脚本
  only:
    - master  // 只监听master分支的代码提交
  tags:
    - pzhuweb  // 要使用哪个runner